<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">Gezocht op</h2>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-bordered table-hover table-striped">
                    <thead class="thead-dark">
                    <tr>
                        <th>Zoekwoord</th>
                        <th>Laatst gezocht op</th>
                        <th>Aantal keer gezocht</th>
                        <th class="text-center"><i class="fas fa-cogs"></i></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (count($searchPhrases) > 0) { ?>
                        <?php foreach ($searchPhrases as $searchPhrase) { ?>
                            <tr>
                                <td><?php echo $searchPhrase->getSearchPhrase(); ?></td>
                                <td><?php echo(is_object($searchPhrase->getDateSearched()) ? $searchPhrase->getDateSearched()->format('d-m-Y') : ''); ?></td>
                                <td><?php echo $searchPhrase->getCount(); ?></td>
                                <td class="text-center">
                                    <a class="btn btn-sm btn-danger" href="
                       <?= $this->url('beheer/search', ['action' => 'delete', 'id' => $searchPhrase->getId()]); ?>">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                        <td colspan="4" class="text-center">Er is nog niet gezocht. Treurig niet?</td>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  mt-4 p-4">
                <?= $this->paginationControl($searchPhrases,
                    'Sliding',
                    'layout/paginator',
                    array('route' => 'beheer/blog')) ?>
            </div>
        </div>
    </div>
</div>