<?php
$this->mainMenu()->setActiveItemId('search');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Search' => $this->url('beheer/search'),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">SEARCH BEHEER</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Zoekwoord</th>
                <th>Laatst gezocht op</th>
                <th>Aantal keer gezocht</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php if (count($searchPhrases) > 0) { ?>
                <?php foreach ($searchPhrases AS $searchPhrase) { ?>
                    <tr>
                        <td><?php echo $searchPhrase->getSearchPhrase(); ?></td>
                        <td><?php echo(is_object($searchPhrase->getDateSearched()) ? $searchPhrase->getDateSearched()->format('d-m-Y') : ''); ?></td>
                        <td><?php echo $searchPhrase->getCount(); ?></td>
                        <td class="text-center">
                            <a class="btn btn-sm btn-danger" href="
                       <?= $this->url('beheer/search', ['action' => 'delete', 'id' => $searchPhrase->getId()]); ?>">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <td colspan="4" class="text-center">Er is nog niet gezocht. Treurig niet?</td>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>